(function () {
  'use strict';

  function initVidewayAcademy() {
    var root = document.getElementById('vw-ghl-landing');
    if (!root || root.dataset.vwReady === '1') return;
    root.dataset.vwReady = '1';

    var translations = {
      en: {
        meta: {
          title: "Pagurai - High-Performance AI Ads & Content for Ecommerce",
          description: "We create ecommerce ads, product videos, and visual content designed to generate sales, produce more variants, and help you scale without multiplying your production costs."
        },
        nav: {
          cta: "Quote your next campaign"
        },
        hero: {
          label: "For ecommerce looking to sell more and spend less",
          title: '<span class="vw-line">Boost your <span class="vw-hero-accent-line">sales</span></span><span class="vw-line">and cut your production <span class="vw-hero-accent-line">costs</span></span><span class="vw-line">by up to 75%</span>',
          subheadline: 'More production · More variants · Less costs',
          desc: "Tired of spending thousands on models and shoots? While others spend $3,000, $6,000, or even $12,000 per campaign, we create your ads and content with AI. Lower costs. Higher sales.",
          badge1: "<strong>High-performance<br>ads</strong><span>Designed to generate sales</span>",
          badge2: "<strong>Unlimited variants<br>for ad testing</strong><span>Scale your campaigns fast</span>",
          badge3: "<strong>Lower production<br>cost</strong><span>No models or studios</span>",
          videoPill1: "Created with AI",
          videoPill2: "Produced in record time",
          videoCaptionTitle: "High-impact AI ads & videos.",
          videoCaptionDesc: "This is the type of content that stops the scroll and drives purchases.",
          step1Kicker: "01 · Concept",
          step1Title: "Irresistible product hook",
          step2Kicker: "02 · Optimization",
          step2Title: "Direct-response variants",
          step3Kicker: "03 · Result",
          step3Title: "Ads ready to convert",
          cta: '<span class="vw-btn-glow"></span>I WANT TO CUT MY COSTS AND SELL MORE',
          ctaNote: "Leave us your details. We will respond in less than 24 hours."
        },
        logos: {
          text: "For ecommerce, brands, and agencies that need to produce more content without increasing their costs."
        },
        opportunity: {
          label: "Production costs are holding you back",
          title: 'Why pay thousands <span class="vw-accent">for a single ad?</span>',
          subtitle: "In the US, a shoot can cost between $3,000 and $12,000. And you can't rely on just one video. You need continuous content. We reduce those costs by up to 75%. More margin for you. More ads running. More sales.",
          card1Title: "For Ecommerce",
          card1Text: "Get continuous content and fresh ads without relying on slow and expensive traditional shoots.",
          card2Title: "More Margin",
          card2Text: "Cut production costs by up to 75%, freeing up budget to scale your campaigns and increase your sales.",
          card3Title: "More Ads Running",
          card3Text: "Test dozens of AI creatives to find winning hooks quickly and consistently.",
          cta: '<span class="vw-btn-glow"></span>I WANT MORE SALES FOR MY ECOMMERCE',
          ctaNote: "Without traditional production costs."
        },
        showcase: {
          label: "How it works",
          title: 'Goodbye models, <span class="vw-accent">hello results.</span>',
          subtitle: "We create your ads with AI-generated models, at no extra cost. We optimize every creative to capture attention and drive product purchases.",
          pill1: "AI Ads",
          pill2: "AI Variations",
          pill3: "Smart Production",
          block1Kicker: "Ads with AI Models",
          block1Title: "AI-Generated<br class=\"vw-desktop-only-br\"> Models",
          block1Text: "We create hyper-realistic product ads using models generated by artificial intelligence. Save on agency contracts, photographers, and shoot logistics.",
          block1Bullet1: "Hyper-realistic models without agency costs",
          block1Bullet2: "Variations in gender, age, and style",
          block1Bullet3: "Perfect for Meta Ads and TikTok campaigns",
          block1Cta: '<span class="vw-btn-glow"></span>I WANT ADS THAT DRIVE SALES',
          block1Note: "Ideal for ecommerce brands looking to scale conversions.",
          block2Kicker: "Multiply Your Ads",
          block2Title: "Multiply your ads without multiplying your costs",
          block2Text: "AI allows us to produce dozens of variations so you can test constantly without skyrocketing your operational costs.",
          block2Bullet1: "More creative variants for constant testing",
          block2Bullet2: "Less ad fatigue in your campaigns",
          block2Bullet3: "Higher probability of finding winning creatives",
          block2Cta: '<span class="vw-btn-glow"></span>I WANT MORE VARIANTS FOR MY ADS',
          block2Note: "Designed for stores that test ads constantly.",
          block3Kicker: "Agile Production",
          block3Title: "Goodbye slow production",
          block3Text: "Forget waiting weeks for a single video. Get creatives ready for your advertising campaigns in record time.",
          block3Bullet1: "Creative delivery in days, not weeks",
          block3Bullet2: "Lower editing and digital post-production costs",
          block3Bullet3: "Creative strategies focused on real results",
          block3Cta: '<span class="vw-btn-glow"></span>I WANT SMART PRODUCTION NOW',
          block3Note: "Maximize your digital creative budget."
        },
        features: {
          label: "What you get",
          title: 'Multiply your ads <span class="vw-accent">without multiplying your costs.</span>',
          subtitle: "You get a smart production system designed to help you get more variants, more tests, and more sales without skyrocketing your budget.",
          strip1Title: "Launch campaigns faster",
          strip1Text: "Launch your campaigns and test new angles in record time. Go from idea to final ad without traditional production delays.",
          strip2Title: "Test more variants",
          strip2Text: "Constant testing is the key to scaling. We create multiple versions of your ads so you can find the winning creative.",
          strip3Title: "Cut production costs",
          strip3Text: "Save up to 75% in production costs by eliminating the need to hire models, rent studios, and coordinate shoots.",
          strip4Title: "Increase your sales",
          strip4Text: "Every piece is designed to capture scroll attention, highlight product benefits, and drive conversions."
        },
        whyus: {
          label: "Why us",
          title: 'We are not just AI, <span class="vw-accent">we are your sales partner.</span>',
          subtitle: "We don't just make videos, we make your products sell. We design advertising assets optimized for return on investment.",
          pill1: "Sales Assets",
          pill2: "Conversion Strategy",
          pill3: "Creative Variants",
          pill4: "Campaign Optimization",
          pill5: "AI Art Direction",
          check1: "Most agencies deliver generic videos. We create sales assets focused on conversion.",
          check2: "AI-generated models that connect with your ideal audience, cutting production costs by up to 75%.",
          check3: "Agile advertising structure so you can test more variants, run more tests, and generate more sales.",
          cta: '<span class="vw-btn-glow"></span>I want to build sales assets for my brand',
          ctaNote: "Yes: besides attractive videos, we create a visual system optimized for your conversion."
        },
        comparison: {
          label: "Disruption is already here",
          title: 'Two paths for your creatives. <span class="vw-accent">Only one allows you to scale.</span>',
          subtitle: "Producing ecommerce content traditionally involves inflated costs, slow times, and limited tests. Pagurai changes the game by cutting your costs by up to 75% and multiplying your creative variants.",
          cardTraditionalTitle: "The traditional path",
          cardTraditionalBullet1: "Spend $3,000 to $12,000 per campaign",
          cardTraditionalBullet2: "Pay for models and traditional shoots",
          cardTraditionalBullet3: "Wait weeks for a single video",
          cardTraditionalBullet4: "Profit margin reduced by high costs",
          cardPaguraiTitle: "The Pagurai path",
          cardPaguraiBullet1: "Up to 75% less in production costs",
          cardPaguraiBullet2: "AI-generated models at no extra cost",
          cardPaguraiBullet3: "Fast production and unlimited variants",
          cardPaguraiBullet4: "Higher margin and more ads running",
          cta: '<span class="vw-btn-glow"></span>I WANT TO CUT MY COSTS AND SELL MORE',
          note: "Leave us your details. We will respond in less than 24 hours."
        },
        services: {
          label: "Our Services",
          title: 'Creative services tailored to <span class="vw-accent">your sales volume</span>',
          subtitle: "Our creative services and packages are designed to help you sell more. Choose the option that best fits the volume and speed of ad testing your brand needs.",
          tier1Label: "Option 1",
          tier1Name: "One-Off Creatives",
          tier1Desc: "Product videos and short hook ads ideal for product launches or specific seasonal campaigns.",
          tier2BadgeFull: "MOST POPULAR",
          tier2BadgeShort: "POPULAR",
          tier2Label: "Option 2",
          tier2Name: "Creative Retainers",
          tier2Desc: "Monthly packages for ecommerce brands that need constant volume, speed, and ongoing creative concepts.",
          tier3Label: "Option 3",
          tier3Name: "AI Direction",
          tier3Desc: "Creative direction, full high-impact campaigns, massive variant management, and high-level advertising strategy.",
          cta: '<span class="vw-btn-glow"></span>I WANT TO START TODAY',
          ctaNote: "Indicative prices based on product catalog complexity and monthly ad volume."
        },
        stats: {
          label: "Results",
          title: 'It\'s not just content, <span class="vw-accent">it\'s content that sells.</span>',
          subtitle: "Our clients have seen sales increases of up to 75% with our AI ads. You don't just save on production. Every ad we make is optimized to capture attention and drive purchases.",
          stat1Label: "Average click-through rate achieved on optimized ads",
          stat2Label: "Reduction in customer acquisition cost in test campaigns",
          stat3Label: "Average return on ad spend achieved"
        },
        about: {
          label: "Your Creative Partner",
          title: 'About <span class="vw-accent">Pagurai</span>',
          subtitle: "We're a global team of specialists in advertising, ecommerce, creative production, and artificial intelligence.",
          desc: "Instead of building large traditional production teams, we leverage cutting-edge AI and modern workflows to produce at a scale that would normally require significantly more people, time, and resources.<br><br>We stay at the forefront of technology so our clients can move faster, create more, and spend less.",
          cred1: "Global talent with experience across multiple industries",
          cred2: "Experts in ecommerce, advertising, creative production, and AI",
          cred3: "Built to produce more with fewer resources"
        },
        faq: {
          label: "Frequently Asked Questions",
          title: "The most common questions",
          q1: "Do I need to record content?",
          a1: "Not necessarily. We can work with your existing product assets and use AI models to generate high-impact ads.",
          q2: "How do you reduce costs by up to 75%?",
          a2: "By eliminating real model hiring, photographers, studio rentals, logistics, and slow post-production, we pass those savings directly to you.",
          q3: "What type of content do you create?",
          a3: "Ads for Meta, TikTok, product videos, and variants optimized for ad testing.",
          q4: "Can I request multiple versions?",
          a4: "Yes, our approach is based on creating variants so you can run more tests and find winning ads.",
          q5: "Are AI models realistic?",
          a5: "Yes, we use next-generation AI technology to create realistic models that represent your brand professionally and naturally."
        },
        footercta: {
          label: "Your next campaign can cost less and sell more.",
          title: 'Multiply your ads. <span class="vw-accent">Reduce your costs and sell more.</span>',
          subtitle: "Let us show you how to create high-performance advertising content with AI and virtual models, cutting your costs by up to 75%.",
          cta: '<span class="vw-btn-glow"></span>I WANT TO GROW MY ECOMMERCE',
          note: "We will connect you with a real person. No obligation."
        },
        footer: {
          text1: "Copyright by Corporación Paguro SAS ™ 2026 | <a data-vw-link=\"privacy\" target=\"_blank\" rel=\"noopener noreferrer\" data-i18n=\"footer.privacyLink\">PRIVACY POLICY</a>",
          privacyLink: "PRIVACY POLICY",
          text2: "This site is not a part of the Facebook website or Facebook Inc. Additionally, this site is not endorsed by Facebook in any way. FACEBOOK is a trademark of Facebook Inc.",
          text3: "Corporación Paguro SAS and this opportunity are not affiliated with or endorsed by any company. Earnings and income representations mentioned by Corporación Paguro SAS, its promoters, sponsors, members, or owners are aspirational examples and do not guarantee specific results. Each individual's success depends on various factors, such as their individual capacity, work ethic, business skills, experience, motivation, diligence in applying Corporación Paguro SAS's programs, and external factors like the economy and business risks.",
          text4: "Corporación Paguro SAS assumes no responsibility for your actions or decisions. The use of our products and services should be based on your own diligence and analysis. By accessing this page or any content from Corporación Paguro SAS, you agree that Corporación Paguro SAS is not liable for any results you obtain using our resources."
        },
        form: {
          progressLabel: "Progress...",
          title: "Boost your ecommerce sales with AI ads:",
          subtitle: "Leave us your details and we will analyze your product for free",
          goalLabel: "What is your main current goal? *",
          goalOpt1: "Reduce production costs for my ads",
          goalOpt2: "Scale sales by testing more creative variants",
          errRadio: "Please select an option.",
          nameLabel: "Name *",
          namePlaceholder: "First Name",
          errName: "Name is required.",
          emailLabel: "Email Address *",
          emailPlaceholder: "Company contact email",
          errEmail: "Please enter a valid email address.",
          phoneLabel: "Phone Number *",
          phonePlaceholder: "Phone number to schedule call",
          errPhone: "Please enter a valid phone number.",
          consentLabel: "I agree to receive occasional communications from Pagurai. We do not spam or share your information. *",
          submit: "I WANT TO START WITH PAGURAI!",
          policyLink: "Privacy Policy",
          sending: "Sending...",
          submitted: "Sent!"
        }
      },
      es: {
        meta: {
          title: "Pagurai - Anuncios y Contenido con IA de Alto Rendimiento para Ecommerce",
          description: "Creamos anuncios, videos de producto y contenido visual para ecommerce diseñados para generar ventas, producir más variantes y ayudarte a escalar sin multiplicar tus gastos de producción."
        },
        nav: {
          cta: "Cotiza tu próxima campaña"
        },
        hero: {
          label: "Para e-commerce que quieren vender más y gastar menos",
          title: '<span class="vw-line">Aumenta tus <span class="vw-hero-accent-line">ventas</span></span><span class="vw-line">y reduce tus <span class="vw-hero-accent-line">costos</span></span><span class="vw-line">de producción</span><span class="vw-line">hasta un 75%</span>',
          subheadline: 'Más producción · Más variantes · Menos costos',
          desc: "¿Cansado de gastar miles en modelos y producciones? Mientras otros gastan $3,000, $6,000 o incluso $12,000 por cada campaña, nosotros creamos tus anuncios y contenido con IA. Menos costos. Más ventas.",
          badge1: "<strong>Anuncios de alto<br>rendimiento</strong><span>Diseñados para generar ventas</span>",
          badge2: "<strong>Variantes ilimitadas<br>para ad testing</strong><span>Escala tus campañas rápido</span>",
          badge3: "<strong>Menor costo de<br>producción</strong><span>Sin modelos ni estudios</span>",
          videoPill1: "Creado con IA",
          videoPill2: "Producido en tiempo récord",
          videoCaptionTitle: "Anuncios y vídeos con IA de alto impacto.",
          videoCaptionDesc: "Ese es el tipo de contenido que hace que tu cliente pare el scroll y compre.",
          step1Kicker: "01 · Concepto",
          step1Title: "Hook de producto irresistible",
          step2Kicker: "02 · Optimización",
          step2Title: "Variantes de venta directa",
          step3Kicker: "03 · Resultado",
          step3Title: "Anuncios listos para convertir",
          cta: '<span class="vw-btn-glow"></span>QUIERO REDUCIR MIS COSTOS Y VENDER MÁS',
          ctaNote: "Déjanos tus datos. Te responderemos en menos de 24 horas."
        },
        logos: {
          text: "Para ecommerce, marcas y agencias que necesitan producir más contenido sin aumentar sus costos."
        },
        opportunity: {
          label: "El costo de producción te está frenando",
          title: '¿Por qué pagar miles <span class="vw-accent">por un solo anuncio?</span>',
          subtitle: "En EE. UU., una producción puede costarte entre $3,000 y $12,000. Y no puedes quedarte con un solo video. Necesitas contenido constante. Nosotros reducimos esos costos hasta un 75%. Más margen para ti. Más anuncios en circulación. Más ventas.",
          card1Title: "Para e-commerce",
          card1Text: "Consigue contenido constante y anuncios frescos sin depender de producciones tradicionales lentas y costosas.",
          card2Title: "Más margen para ti",
          card2Text: "Reduce tus costos de producción hasta un 75%, liberando presupuesto para escalar tus campañas y aumentar tus ventas.",
          card3Title: "Más anuncios en circulación",
          card3Text: "Prueba decenas de creatividades con IA para encontrar hooks ganadores de manera rápida y constante.",
          cta: '<span class="vw-btn-glow"></span>QUIERO MÁS VENTAS PARA MI ECOMMERCE',
          ctaNote: "Sin costos de producción tradicionales."
        },
        showcase: {
          label: "Cómo funciona",
          title: 'Adiós a los modelos, <span class="vw-accent">bienvenidos los resultados.</span>',
          subtitle: "Creamos tus anuncios con modelos generados por IA, sin costos extra. Optimizamos cada pieza para captar la atención de tu audiencia y empujar a la compra de tus productos.",
          pill1: "Anuncios con IA",
          pill2: "Variaciones IA",
          pill3: "Producción inteligente",
          block1Kicker: "Anuncios con modelos IA",
          block1Title: "Modelos generados<br class=\"vw-desktop-only-br\"> por IA",
          block1Text: "Creamos anuncios de producto hiperrealistas utilizando modelos generados por inteligencia artificial. Ahorra en contratos de modelos, fotógrafos y logística de rodajes.",
          block1Bullet1: "Modelos hiperrealistas sin costo de agencia",
          block1Bullet2: "Variantes de género, edad y estilo",
          block1Bullet3: "Perfecto para campañas en Meta Ads y TikTok",
          block1Cta: '<span class="vw-btn-glow"></span>QUIERO ANUNCIOS QUE GENEREN VENTAS',
          block1Note: "Ideal para marcas de ecommerce que buscan escalar conversiones.",
          block2Kicker: "Multiplica tus anuncios",
          block2Title: "Multiplica tus anuncios sin multiplicar tus costos",
          block2Text: "La IA nos permite producir decenas de variaciones para que puedas hacer tests de manera constante sin disparar tus costos operativos.",
          block2Bullet1: "Más variantes creativas para testing constante",
          block2Bullet2: "Menos fatiga publicitaria (ad fatigue) en tus campañas",
          block2Bullet3: "Mayor probabilidad de encontrar creatividades ganadoras",
          block2Cta: '<span class="vw-btn-glow"></span>QUIERO MÁS VARIANTES PARA MIS ANUNCIOS',
          block2Note: "Pensado para tiendas que testean anuncios constantemente.",
          block3Kicker: "Producción ágil",
          block3Title: "Adiós a la producción lenta",
          block3Text: "Olvídate de esperar semanas por un solo video. Obtenemos creativos listos para tus campañas publicitarias en tiempo récord.",
          block3Bullet1: "Entrega de creativos en días, no semanas",
          block3Bullet2: "Menos costos de edición y postproducción digital",
          block3Bullet3: "Estrategias creativas orientadas a resultados reales",
          block3Cta: '<span class="vw-btn-glow"></span>QUIERO PRODUCCIÓN INTELIGENTE AHORA',
          block3Note: "Maximiza tu presupuesto creativo digital."
        },
        features: {
          label: "Lo que obtienes",
          title: 'Multiplica tus anuncios <span class="vw-accent">sin multiplicar tus costos.</span>',
          subtitle: "Obtienes un sistema de producción inteligente diseñado para ayudarte a obtener más variantes, más tests y más ventas sin disparar tu presupuesto.",
          strip1Title: "Lanza campañas más rápido",
          strip1Text: "Lanza tus campañas y prueba nuevos ángulos en tiempo récord. De la idea al anuncio final sin los retrasos de la producción tradicional.",
          strip2Title: "Prueba más variantes",
          strip2Text: "El testing constante es la clave para escalar. Creamos múltiples versiones de tus anuncios para que encuentres la creatividad ganadora.",
          strip3Title: "Reduce costos de producción",
          strip3Text: "Ahorra hasta un 75% en costos de producción eliminando la necesidad de contratar modelos, alquilar estudios y coordinar rodajes.",
          strip4Title: "Aumenta tus ventas",
          strip4Text: "Cada pieza está diseñada para captar la atención en el scroll, destacar los beneficios de tu producto y empujar a la conversión."
        },
        whyus: {
          label: "Por qué nosotros",
          title: 'No somos solo IA, <span class="vw-accent">somos tu socio en ventas.</span>',
          subtitle: "No solo hacemos videos, hacemos que tus productos se vendan. Diseñamos activos publicitarios optimizados para el retorno de inversión.",
          pill1: "Activos de Venta",
          pill2: "Estrategia de Conversión",
          pill3: "Variantes Creativas",
          pill4: "Optimización de Campañas",
          pill5: "Dirección de Arte IA",
          check1: "La mayoría de agencias entregan videos genéricos. Nosotros creamos activos de venta enfocados en conversión.",
          check2: "Modelos generados por IA que conectan con tu audiencia ideal, reduciendo costos de producción hasta un 75%.",
          check3: "Estructura publicitaria ágil para que puedas probar más variantes, realizar más tests y generar más ventas.",
          cta: '<span class="vw-btn-glow"></span>Quiero construir activos de venta para mi marca',
          ctaNote: "Sí: además de vídeos atractivos, creamos un sistema visual optimizado para tu conversión."
        },
        comparison: {
          label: "La disrupción ya está aquí",
          title: 'Dos caminos para tus creativos. <span class="vw-accent">Solo uno te permite escalar.</span>',
          subtitle: "Producir contenido para e-commerce de manera tradicional implica costos inflados, tiempos lentos y pruebas limitadas. Pagurai cambia las reglas del juego reduciendo tus costos hasta un 75% y multiplicando tus variantes creativas.",
          cardTraditionalTitle: "El camino tradicional",
          cardTraditionalBullet1: "Gastar de $3,000 a $12,000 por campaña",
          cardTraditionalBullet2: "Pagar por modelos y producciones tradicionales",
          cardTraditionalBullet3: "Esperar semanas por un solo video",
          cardTraditionalBullet4: "Margen de ganancia reducido por altos costos",
          cardPaguraiTitle: "El camino Pagurai",
          cardPaguraiBullet1: "Hasta un 75% menos en costos de producción",
          cardPaguraiBullet2: "Modelos generados por IA sin costos extra",
          cardPaguraiBullet3: "Producción rápida y variantes ilimitadas",
          cardPaguraiBullet4: "Mayor margen y más ventas en circulación",
          cta: '<span class="vw-btn-glow"></span>QUIERO REDUCIR MIS COSTOS Y VENDER MÁS',
          note: "Déjanos tus datos. Te responderemos en menos de 24 horas."
        },
        services: {
          label: "Nuestros Servicios",
          title: 'Servicios creativos adaptados a <span class="vw-accent">tu volumen de venta</span>',
          subtitle: "Nuestros servicios y paquetes creativos están diseñados para ayudarte a vender más. Elige la opción que mejor se adapte al volumen y velocidad de ad testing que requiere tu marca.",
          tier1Label: "Opción 1",
          tier1Name: "Piezas Puntuales",
          tier1Desc: "Videos de producto y anuncios de gancho corto ideales para lanzamientos de producto o campañas específicas de temporada.",
          tier2BadgeFull: "MÁS SOLICITADO",
          tier2BadgeShort: "POPULAR",
          tier2Label: "Opción 2",
          tier2Name: "Retainers Creativos",
          tier2Desc: "Paquetes mensuales para marcas de ecommerce que necesitan volumen constante, velocidad y propuestas creativas continuas.",
          tier3Label: "Opción 3",
          tier3Name: "Dirección IA",
          tier3Desc: "Dirección creativa, campañas completas de gran impacto, gestión de variantes masivas y estrategia publicitaria de alto nivel.",
          cta: '<span class="vw-btn-glow"></span>QUIERO EMPEZAR HOY',
          ctaNote: "Precios indicativos según la complejidad del catálogo de productos y volumen de anuncios mensuales."
        },
        stats: {
          label: "Resultados",
          title: 'No es solo contenido, <span class="vw-accent">es contenido que vende.</span>',
          subtitle: "Nuestros clientes han visto aumentos de ventas de hasta un 75% con nuestros anuncios IA. No solo ahorras en producción. Cada anuncio que hacemos está optimizado para captar la atención y empujar a la compra.",
          stat1Label: "Tasa de clics promedio lograda en anuncios optimizados",
          stat2Label: "Reducción del costo de adquisición en campañas de testeo",
          stat3Label: "Retorno de inversión publicitaria promedio alcanzado"
        },
        about: {
          label: "Tu socio creativo",
          title: 'Sobre <span class="vw-accent">Pagurai</span>',
          subtitle: "Somos un equipo global de especialistas en publicidad, comercio electrónico, producción creativa e inteligencia artificial.",
          desc: "En lugar de construir grandes equipos de producción tradicionales, aprovechamos la IA de última generación y los flujos de trabajo modernos para producir a una escala que normalmente requeriría significativamente más personas, tiempo y recursos.<br><br>Nos mantenemos a la vanguardia de la tecnología para que nuestros clientes puedan avanzar más rápido, crear más y gastar menos.",
          cred1: "Talento global con experiencia en múltiples industrias",
          cred2: "Expertos en comercio electrónico, publicidad, producción creativa e IA",
          cred3: "Creados para producir más con menos recursos"
        },
        faq: {
          label: "Preguntas frecuentes",
          title: "Te resolvemos las más usuales",
          q1: "¿Necesito grabar contenido?",
          a1: "No necesariamente. Podemos trabajar con el material actual de tu producto y usar modelos de IA para generar anuncios de alto impacto.",
          q2: "¿Cómo reducen los costos hasta un 75%?",
          a2: "Al eliminar la contratación de modelos reales, fotógrafos, alquileres de estudios, logística y postproducción lenta, pasamos esos ahorros directamente a ti.",
          q3: "¿Qué tipo de contenido crean?",
          a3: "Anuncios para Meta, TikTok, videos de producto y variantes optimizadas para ad testing.",
          q4: "¿Puedo solicitar varias versiones?",
          a4: "Sí, nuestro enfoque se basa en crear variantes para que puedas realizar más tests y encontrar anuncios ganadores.",
          q5: "¿Los modelos de IA son realistas?",
          a5: "Sí, utilizamos tecnología de IA de última generación para crear modelos realistas que representen a tu marca de manera profesional y natural."
        },
        footercta: {
          label: "Tu próxima campaña puede costar menos y vender más.",
          title: 'Multiplica tus anuncios. <span class="vw-accent">Reduce tus costos y vende más.</span>',
          subtitle: "Déjanos mostrarte cómo crear contenido publicitario de alto rendimiento con IA y modelos virtuales, reduciendo tus costos hasta un 75%.",
          cta: '<span class="vw-btn-glow"></span>QUIERO HACER CRECER MI ECOMMERCE',
          note: "Te pondremos en contacto con una persona real. Sin compromiso."
        },
        footer: {
          text1: "Copyrights por Corporación Paguro SAS ™ 2026 | <a data-vw-link=\"privacy\" target=\"_blank\" rel=\"noopener noreferrer\" data-i18n=\"footer.privacyLink\">POLÍTICA DE PRIVACIDAD</a>",
          privacyLink: "POLÍTICA DE PRIVACIDAD",
          text2: "Esta página no forma parte del sitio web de Facebook ni está afiliada a Facebook Inc. Además, este sitio no está respaldado de ninguna manera por Facebook. FACEBOOK es una marca registrada de Facebook Inc.",
          text3: "Corporación Paguro SAS y esta formación u oportunidad no están afiliados ni respaldados por ninguna empresa. Las ganancias y representaciones de ingresos mencionadas por Corporación Paguro SAS, sus promotores, patrocinadores, miembros o propietarios son ejemplos aspiracionales y no garantizan resultados específicos. El éxito de cada persona depende de diversos factores, como su capacidad individual, ética laboral, habilidades empresariales, experiencia, motivación, diligencia en la aplicación de los programas de Corporación Paguro SAS, así como de factores externos como la economía y los riesgos asociados a la actividad empresarial.",
          text4: "Corporación Paguro SAS no asume responsabilidad por tus acciones o decisiones. El uso de nuestros productos y servicios debe basarse en tu propia diligencia y análisis. Al acceder a esta página o cualquier contenido de Corporación Paguro SAS, aceptas que Corporación Paguro SAS no es responsable por los resultados que obtengas al utilizar nuestros recursos."
        },
        form: {
          progressLabel: "Progreso...",
          title: "Impulsa las ventas de tu ecommerce con anuncios de IA:",
          subtitle: "Déjanos tus datos y analizaremos tu producto gratis",
          goalLabel: "¿Cuál es tu principal objetivo actual? *",
          goalOpt1: "Reducir costes de producción de mis anuncios",
          goalOpt2: "Escalar ventas probando más variantes creativas",
          errRadio: "Por favor, selecciona una opción.",
          nameLabel: "Nombre *",
          namePlaceholder: "Nombre",
          errName: "El nombre es requerido.",
          emailLabel: "Correo Electrónico *",
          emailPlaceholder: "Correo de contacto de tu empresa",
          errEmail: "Por favor, introduce un correo válido.",
          phoneLabel: "Número de Teléfono *",
          phonePlaceholder: "Teléfono para coordinar llamada",
          errPhone: "Por favor, introduce un teléfono válido.",
          consentLabel: "Acepto recibir comunicaciones ocasionales de Pagurai. No realizamos spam ni compartimos tu información. *",
          submit: "¡QUIERO EMPEZAR CON PAGURAI!",
          policyLink: "Política de Privacidad",
          sending: "Enviando...",
          submitted: "Enviado!"
        }
      }
    };

    var currentLang = localStorage.getItem('pagurai_pref_lang') || 'en';

    function getTranslation(lang, key) {
      var parts = key.split('.');
      var current = translations[lang];
      for (var i = 0; i < parts.length; i++) {
        if (current && current[parts[i]] !== undefined) {
          current = current[parts[i]];
        } else {
          return null;
        }
      }
      return current;
    }

    function applyTranslations(lang) {
      document.documentElement.lang = lang;

      // Update standard attributes data-i18n
      document.querySelectorAll('[data-i18n]').forEach(function (el) {
        var key = el.getAttribute('data-i18n');
        var val = getTranslation(lang, key);
        if (val) {
          if (val.indexOf('<') !== -1 || val.indexOf('&') !== -1) {
            el.innerHTML = val;
          } else {
            el.textContent = val;
          }
        }
      });

      // Update placeholders data-i18n-placeholder
      document.querySelectorAll('[data-i18n-placeholder]').forEach(function (el) {
        var key = el.getAttribute('data-i18n-placeholder');
        var val = getTranslation(lang, key);
        if (val) {
          el.setAttribute('placeholder', val);
        }
      });

      // Update document title and metadata
      var pageTitle = getTranslation(lang, 'meta.title');
      if (pageTitle) {
        document.title = pageTitle;
        var metaTitle = document.querySelector('meta[name="title"]');
        if (metaTitle) metaTitle.setAttribute('content', pageTitle);
        var ogTitle = document.querySelector('meta[property="og:title"]');
        if (ogTitle) ogTitle.setAttribute('content', pageTitle);
      }

      var pageDesc = getTranslation(lang, 'meta.description');
      if (pageDesc) {
        var metaDesc = document.querySelector('meta[name="description"]');
        if (metaDesc) metaDesc.setAttribute('content', pageDesc);
        var ogDesc = document.querySelector('meta[property="og:description"]');
        if (ogDesc) ogDesc.setAttribute('content', pageDesc);
      }

      // Update switcher buttons active state
      document.querySelectorAll('[data-vw-lang-btn]').forEach(function (btn) {
        var btnLang = btn.getAttribute('data-vw-lang-btn');
        btn.classList.toggle('active', btnLang === lang);
      });

      // Update Submit Button specifically since it's interactive
      var submitBtn = document.querySelector('.vw-popup-submit-btn');
      if (submitBtn && !submitBtn.disabled) {
        submitBtn.textContent = getTranslation(lang, 'form.submit') || 'I WANT TO START WITH PAGURAI!';
      }
    }

    // Initialize switcher buttons listeners
    document.querySelectorAll('[data-vw-lang-btn]').forEach(function (btn) {
      btn.addEventListener('click', function () {
        var selectedLang = btn.getAttribute('data-vw-lang-btn');
        if (selectedLang !== currentLang) {
          currentLang = selectedLang;
          localStorage.setItem('pagurai_pref_lang', currentLang);
          applyTranslations(currentLang);
        }
      });
    });

    // Apply translations on load
    applyTranslations(currentLang);

    var config = window.VW_GHL_CONFIG || {};
    var assets = config.assets || {};
    var links = config.links || {};
    var videos = config.videos || {};

    // Wire asset images
    root.querySelectorAll('[data-vw-asset]').forEach(function (el) {
      var key = el.getAttribute('data-vw-asset');
      if (assets[key]) {
        el.setAttribute('src', assets[key]);
      }
    });

    // Wire privacy policy links
    root.querySelectorAll('[data-vw-link]').forEach(function (el) {
      var key = el.getAttribute('data-vw-link');
      if (links[key]) {
        el.setAttribute('href', links[key]);
      }
    });

    // Try playing muted videos inline
    function tryPlayVideo(video) {
      if (!video || !video.getAttribute('src')) return;
      video.muted = true;
      video.defaultMuted = true;
      video.autoplay = true;
      video.loop = true;
      video.playsInline = true;
      video.setAttribute('muted', '');
      video.setAttribute('autoplay', '');
      video.setAttribute('loop', '');
      video.setAttribute('playsinline', '');
      video.setAttribute('webkit-playsinline', '');

      try {
        var p = video.play();
        if (p && p.catch) {
          p.catch(function () { });
        }
      } catch (e) { }
    }

    // Wire MP4 videos with poster fallbacks
    function wireVideo(key) {
      var video = root.querySelector('[data-vw-video="' + key + '"]');
      if (!video) return;

      var posterKey = video.getAttribute('data-vw-poster');
      var url = (videos[key] || '').trim();
      var poster = assets[posterKey] || '';
      var wrap = video.closest('[data-vw-video-wrap]');

      if (poster) {
        video.setAttribute('poster', poster);
      }

      video.muted = true;
      video.defaultMuted = true;
      video.loop = true;
      video.autoplay = true;
      video.playsInline = true;
      video.setAttribute('muted', '');
      video.setAttribute('autoplay', '');
      video.setAttribute('loop', '');
      video.setAttribute('playsinline', '');
      video.setAttribute('webkit-playsinline', '');

      if (url) {
        video.setAttribute('src', url);
        if (wrap) {
          wrap.classList.add('vw-video-ready');
        }
        try {
          video.load();
        } catch (e) { }
        tryPlayVideo(video);
        video.addEventListener('loadeddata', function () { tryPlayVideo(video); }, { once: true });
        video.addEventListener('canplay', function () { tryPlayVideo(video); }, { once: true });
        setTimeout(function () { tryPlayVideo(video); }, 250);
        setTimeout(function () { tryPlayVideo(video); }, 1000);
      }
    }

    wireVideo('hero');
    wireVideo('vertical1');
    wireVideo('vertical2');
    wireVideo('vertical3');

    // Button mouse glow effect coordinates
    root.querySelectorAll('.vw-cta-btn').forEach(function (btn) {
      if (!btn.querySelector('.vw-btn-glow')) {
        var glow = document.createElement('span');
        glow.className = 'vw-btn-glow';
        btn.insertBefore(glow, btn.firstChild);
      }
      btn.addEventListener('pointermove', function (e) {
        var rect = btn.getBoundingClientRect();
        btn.style.setProperty('--mx', (e.clientX - rect.left) + 'px');
        btn.style.setProperty('--my', (e.clientY - rect.top) + 'px');
      });
    });

    // Card mouse glow effect coordinates
    document.addEventListener('pointermove', function (e) {
      root.querySelectorAll('.vw-glow-card').forEach(function (card) {
        var rect = card.getBoundingClientRect();
        card.style.setProperty('--glow-x', (e.clientX - rect.left) + 'px');
        card.style.setProperty('--glow-y', (e.clientY - rect.top) + 'px');
      });
    });

    // Intersection observers for animations
    if ('IntersectionObserver' in window) {
      // General scroll fade-ins
      var revealObserver = new IntersectionObserver(function (entries) {
        entries.forEach(function (entry) {
          if (entry.isIntersecting) {
            entry.target.classList.add('vw-visible');
          }
        });
      }, { threshold: 0.12, rootMargin: '0px 0px -50px 0px' });

      root.querySelectorAll('.vw-reveal, .vw-reveal-stagger').forEach(function (el) {
        revealObserver.observe(el);
      });

      // Accent text reveals
      var accentObserver = new IntersectionObserver(function (entries, obs) {
        entries.forEach(function (entry) {
          if (entry.isIntersecting) {
            entry.target.classList.add('vw-animated');
            obs.unobserve(entry.target);
          }
        });
      }, { threshold: 0.28 });

      root.querySelectorAll('.vw-accent-reveal').forEach(function (el) {
        accentObserver.observe(el);
      });

      // Instantly animate hero accents
      requestAnimationFrame(function () {
        requestAnimationFrame(function () {
          root.querySelectorAll('.vw-hero-accent-line').forEach(function (el) {
            el.classList.add('vw-animated');
          });
        });
      });

      // Floating badges fade in
      var badgeObserver = new IntersectionObserver(function (entries) {
        entries.forEach(function (entry) {
          if (entry.isIntersecting) {
            entry.target.classList.add('vw-badges-visible');
          }
        });
      }, { threshold: 0.3 });

      root.querySelectorAll('[data-vw-badges]').forEach(function (el) {
        badgeObserver.observe(el);
      });

      // Feature strip lists slide in
      var featureObserver = new IntersectionObserver(function (entries) {
        entries.forEach(function (entry) {
          if (entry.isIntersecting) {
            entry.target.classList.add('vw-in-view');
          }
        });
      }, { threshold: 0.18, rootMargin: '0px 0px -80px 0px' });

      root.querySelectorAll('[data-vw-feature]').forEach(function (el) {
        featureObserver.observe(el);
      });

      // Hand drawn oval path animation
      var ovalWrap = root.querySelector('[data-vw-oval]');
      if (ovalWrap) {
        var ovalObserver = new IntersectionObserver(function (entries, obs) {
          entries.forEach(function (entry) {
            if (entry.isIntersecting) {
              ovalWrap.classList.add('vw-drawn');
              obs.unobserve(ovalWrap);
            }
          });
        }, { threshold: 0.38 });
        ovalObserver.observe(ovalWrap);
      }

      // Stats counters animation
      var counterObserver = new IntersectionObserver(function (entries, obs) {
        entries.forEach(function (entry) {
          if (!entry.isIntersecting) return;
          var el = entry.target;
          if (el.dataset.vwCounted === '1') return;
          el.dataset.vwCounted = '1';

          var target = parseInt(el.dataset.target || '0', 10);
          var suffix = el.dataset.suffix || '';
          var duration = 1600;
          var start = performance.now();

          function render(now) {
            var progress = Math.min((now - start) / duration, 1);
            var eased = 1 - Math.pow(1 - progress, 3);
            var current = Math.round(eased * target);
            if (suffix === '-90s') {
              el.textContent = current + '-90s';
            } else {
              el.textContent = current + suffix;
            }
            if (progress < 1) {
              requestAnimationFrame(render);
            }
          }
          requestAnimationFrame(render);
          obs.unobserve(el);
        });
      }, { threshold: 0.5 });

      root.querySelectorAll('[data-vw-counter]').forEach(function (el) {
        counterObserver.observe(el);
      });

      // Autoplay videos when they scroll into viewport
      var videoObserver = new IntersectionObserver(function (entries) {
        entries.forEach(function (entry) {
          var video = entry.target;
          if (!video.getAttribute('src')) return;
          if (entry.isIntersecting) {
            tryPlayVideo(video);
          }
        });
      }, { threshold: 0.05 });

      root.querySelectorAll('video[data-vw-video]').forEach(function (video) {
        videoObserver.observe(video);
      });

    } else {
      // Fallback if IntersectionObserver is not supported
      root.querySelectorAll('.vw-reveal, .vw-reveal-stagger').forEach(function (el) { el.classList.add('vw-visible'); });
      root.querySelectorAll('.vw-accent-reveal, .vw-hero-accent-line').forEach(function (el) { el.classList.add('vw-animated'); });
      root.querySelectorAll('[data-vw-feature]').forEach(function (el) { el.classList.add('vw-in-view'); });
    }

    // FAQ Accordion click triggers
    root.querySelectorAll('.vw-faq-question').forEach(function (btn) {
      btn.addEventListener('click', function () {
        var item = btn.closest('.vw-faq-item');
        var wasActive = item.classList.contains('vw-active');
        root.querySelectorAll('.vw-faq-item').forEach(function (faq) {
          faq.classList.remove('vw-active');
          var q = faq.querySelector('.vw-faq-question');
          if (q) q.setAttribute('aria-expanded', 'false');
        });
        if (!wasActive) {
          item.classList.add('vw-active');
          btn.setAttribute('aria-expanded', 'true');
        }
      });
    });

    // Nav scrolled style toggling
    var nav = root.querySelector('[data-vw-nav]');
    function updateNav() {
      if (!nav) return;
      if (window.scrollY > 40) {
        nav.classList.add('vw-scrolled');
      } else {
        nav.classList.remove('vw-scrolled');
      }
    }
    updateNav();
    window.addEventListener('scroll', updateNav, { passive: true });

    // Testimonial / Video Carousel on Mobile
    function initMobileCarousel() {
      var track = root.querySelector('.vw-video-track');
      var cards = root.querySelectorAll('.vw-vertical-card');
      if (!track || !cards.length) return;

      var active = 0;
      var timer;

      function updateCarousel() {
        cards.forEach(function (card, i) {
          card.classList.toggle('vw-active', i === active);
        });
      }

      function nextCard() {
        active = (active + 1) % cards.length;
        updateCarousel();
      }

      function startAutoplay() {
        clearInterval(timer);
        timer = setInterval(nextCard, 4500);
      }

      track.addEventListener('mouseenter', function () { clearInterval(timer); });
      track.addEventListener('mouseleave', startAutoplay);
      startAutoplay();
    }
    initMobileCarousel();

    // Dot Matrix Canvas Generator
    function createDotMatrix(canvas, section, revealFromCenter) {
      if (!canvas || !section) return;
      var ctx = canvas.getContext('2d');
      if (!ctx) return;
      var GRID = 20;
      var DOT_R = 1.5;
      var ACCENT = [0, 152, 255];
      var dots = [];
      var time = 0;
      var raf;

      function hash(x, y) {
        return ((Math.sin(x * 127.1 + y * 311.7) * 43758.5453123) % 1 + 1) % 1;
      }

      function resize() {
        var dpr = window.devicePixelRatio || 1;
        var rect = section.getBoundingClientRect();
        canvas.width = rect.width * dpr;
        canvas.height = rect.height * dpr;
        canvas.style.width = rect.width + 'px';
        canvas.style.height = rect.height + 'px';
        ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
        dots = [];
        var cols = Math.ceil(rect.width / GRID) + 1;
        var rows = Math.ceil(rect.height / GRID) + 1;
        for (var r = 0; r < rows; r++) {
          for (var c = 0; c < cols; c++) {
            dots.push({
              x: c * GRID + GRID / 2,
              y: r * GRID + GRID / 2,
              seed: hash(c, r),
              delay: hash(c + 0.5, r + 0.5)
            });
          }
        }
      }

      function draw() {
        var rect = section.getBoundingClientRect();
        ctx.clearRect(0, 0, rect.width, rect.height);
        time += 0.016;
        var cx = rect.width / 2;
        var cy = rect.height / 2;
        var maxDist = Math.sqrt(cx * cx + cy * cy) || 1;

        for (var i = 0; i < dots.length; i++) {
          var d = dots[i];
          var flicker = Math.sin(time * 3.5 + d.seed * 50) * 0.5 + 0.5;
          var phase = Math.sin(time * 1.5 + d.delay * 12) * 0.5 + 0.5;
          var blink = Math.sin(time * 1.8 + d.seed * 100 + d.delay * 60);
          var blinkOn = blink > (d.seed > 0.7 ? -0.4 : 0.1) ? 1 : 0;
          var baseOpacity;

          if (d.seed > 0.85) {
            baseOpacity = (0.35 + flicker * 0.3) * blinkOn;
          } else if (d.seed > 0.6) {
            baseOpacity = (0.15 + phase * 0.15) * blinkOn;
          } else {
            baseOpacity = (0.04 + flicker * 0.06) * blinkOn;
          }

          var opacity = baseOpacity;

          if (revealFromCenter) {
            var dist = Math.sqrt(Math.pow(d.x - cx, 2) + Math.pow(d.y - cy, 2));
            var revealThreshold = (dist / maxDist) * 3 + d.delay * 0.8;
            var revealProgress = Math.max(0, Math.min(1, (time * 1.2 - revealThreshold)));
            opacity = baseOpacity * revealProgress;
          }

          if (opacity < 0.01) continue;

          var rgb = d.seed > 0.92 ? ACCENT : [255, 255, 255];
          ctx.beginPath();
          ctx.arc(d.x, d.y, DOT_R, 0, Math.PI * 2);
          ctx.fillStyle = 'rgba(' + rgb[0] + ',' + rgb[1] + ',' + rgb[2] + ',' + opacity + ')';
          ctx.fill();
        }
        raf = requestAnimationFrame(draw);
      }

      resize();
      draw();
      window.addEventListener('resize', resize);

      if ('IntersectionObserver' in window) {
        var active = true;
        var observer = new IntersectionObserver(function (entries) {
          entries.forEach(function (entry) {
            if (!entry.isIntersecting && active) {
              cancelAnimationFrame(raf);
              active = false;
            } else if (entry.isIntersecting && !active) {
              active = true;
              draw();
            }
          });
        }, { threshold: 0 });
        observer.observe(section);
      }
    }

    createDotMatrix(root.querySelector('[data-vw-dot="hero"]'), root.querySelector('.vw-hero'), true);
    createDotMatrix(root.querySelector('[data-vw-dot="footer"]'), root.querySelector('.vw-globe-section'), false);

    // pricing tiers particles canvas
    root.querySelectorAll('.vw-tier-particles').forEach(function (canvas) {
      var ctx = canvas.getContext('2d');
      var tier = canvas.closest('.vw-tier');
      if (!ctx || !tier) return;

      var level = parseInt(canvas.getAttribute('data-vw-tier') || '1', 10);
      var count = 25 + level * 12;
      var sparks = [];
      var frame;
      var palette = {
        1: [[0, 152, 255], [77, 184, 255]],
        2: [[77, 184, 255], [179, 224, 255]],
        3: [[253, 224, 71], [77, 184, 255], [0, 152, 255]]
      };

      function resetSpark(s, w, h) {
        s.x = Math.random() * w;
        s.y = h + Math.random() * 20;
        s.vy = -(0.3 + Math.random() * 0.6) * (0.7 + level * 0.2);
        s.vx = (Math.random() - 0.5) * 0.4;
        s.size = 0.6 + Math.random() * 0.8;
        s.life = 0;
        s.maxLife = 120 + Math.random() * 100;
        s.wobbleSpeed = 1 + Math.random() * 2;
        s.wobbleAmp = 0.3 + Math.random() * 0.8;
        var cols = palette[level] || palette[1];
        s.color = cols[Math.floor(Math.random() * cols.length)];
      }

      function resizeTier() {
        var dpr = window.devicePixelRatio || 1;
        var rect = tier.getBoundingClientRect();
        canvas.width = rect.width * dpr;
        canvas.height = rect.height * dpr;
        ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
        sparks = [];
        for (var i = 0; i < count; i++) {
          var s = {};
          resetSpark(s, rect.width, rect.height);
          s.life = Math.random() * s.maxLife;
          sparks.push(s);
        }
      }

      function drawTier() {
        var rect = tier.getBoundingClientRect();
        var w = rect.width;
        var h = rect.height;
        ctx.clearRect(0, 0, w, h);
        for (var i = 0; i < sparks.length; i++) {
          var s = sparks[i];
          s.life++;
          if (s.life > s.maxLife || s.y < -10) {
            resetSpark(s, w, h);
          }
          s.y += s.vy;
          s.x += s.vx + Math.sin(s.life * 0.02 * s.wobbleSpeed) * s.wobbleAmp;
          var progress = s.life / s.maxLife;
          var alpha = progress < 0.1 ? progress / 0.1 : 1 - Math.pow((progress - 0.1) / 0.9, 2);
          var a = alpha * 0.6;
          if (a < 0.02) continue;

          var color = s.color;
          ctx.beginPath();
          ctx.arc(s.x, s.y, s.size * 4, 0, Math.PI * 2);
          ctx.fillStyle = 'rgba(' + color[0] + ',' + color[1] + ',' + color[2] + ',' + (a * 0.08) + ')';
          ctx.fill();

          ctx.beginPath();
          ctx.arc(s.x, s.y, s.size, 0, Math.PI * 2);
          ctx.fillStyle = 'rgba(' + color[0] + ',' + color[1] + ',' + color[2] + ',' + a + ')';
          ctx.fill();
        }
        frame = requestAnimationFrame(drawTier);
      }

      resizeTier();
      drawTier();
      window.addEventListener('resize', resizeTier);

      if ('IntersectionObserver' in window) {
        var live = true;
        var obs = new IntersectionObserver(function (entries) {
          entries.forEach(function (entry) {
            if (!entry.isIntersecting && live) {
              cancelAnimationFrame(frame);
              live = false;
            } else if (entry.isIntersecting && !live) {
              live = true;
              drawTier();
            }
          });
        }, { threshold: 0 });
        obs.observe(tier);
      }
    });

    // Custom Form Popup Modal interactive control
    var popupOverlay = document.getElementById('vw-form-popup');
    var popupCloseBtn = document.getElementById('vw-popup-close-btn');
    var modalForm = document.getElementById('vw-modal-form');

    function openPopupModal() {
      if (popupOverlay) {
        popupOverlay.classList.add('vw-active');
        document.body.style.overflow = 'hidden';
      }
    }

    function closePopupModal() {
      if (popupOverlay) {
        popupOverlay.classList.remove('vw-active');
        document.body.style.overflow = '';
        resetFormErrors();
      }
    }

    // Trigger popup modal when clicking any element with [data-vw-popup]
    document.querySelectorAll('[data-vw-popup]').forEach(function (btn) {
      btn.addEventListener('click', function (e) {
        e.preventDefault();
        openPopupModal();
      });
    });

    // Close when close btn is clicked
    if (popupCloseBtn) {
      popupCloseBtn.addEventListener('click', closePopupModal);
    }

    // Close when overlay BG is clicked
    if (popupOverlay) {
      popupOverlay.addEventListener('click', function (e) {
        if (e.target === popupOverlay) {
          closePopupModal();
        }
      });
    }

    // Form inputs error states resets
    function resetFormErrors() {
      if (!modalForm) return;
      modalForm.querySelectorAll('.vw-form-group').forEach(function (group) {
        group.classList.remove('vw-invalid');
      });
      var errRadio = document.getElementById('err-radio');
      if (errRadio) errRadio.style.display = 'none';
    }

    // Modal Form submission validation and redirect action
    if (modalForm) {
      modalForm.addEventListener('submit', function (e) {
        e.preventDefault();
        resetFormErrors();

        var isValid = true;

        // 1. Validate Radio Choice
        var radios = modalForm.querySelectorAll('input[name="qu_te_interesa_ms_ahora_mismo"]');
        var radioSelected = false;
        var selectedVal = '';
        radios.forEach(function (r) {
          if (r.checked) {
            radioSelected = true;
            selectedVal = r.value;
          }
        });
        if (!radioSelected) {
          var errRadio = document.getElementById('err-radio');
          if (errRadio) errRadio.style.display = 'block';
          isValid = false;
        }

        // 2. Validate Name
        var inputNombre = document.getElementById('vw-input-nombre');
        if (inputNombre && !inputNombre.value.trim()) {
          document.getElementById('group-nombre').classList.add('vw-invalid');
          isValid = false;
        }

        // 3. Validate Email
        var inputEmail = document.getElementById('vw-input-email');
        var emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
        if (inputEmail && (!inputEmail.value.trim() || !emailPattern.test(inputEmail.value.trim()))) {
          document.getElementById('group-email').classList.add('vw-invalid');
          isValid = false;
        }

        // 4. Validate Phone
        var inputPhone = document.getElementById('vw-input-phone');
        if (inputPhone && !inputPhone.value.trim()) {
          document.getElementById('group-phone').classList.add('vw-invalid');
          isValid = false;
        }

        // 5. Validate Consent Checkbox
        var inputTerms = document.getElementById('vw-input-terms');
        if (inputTerms && !inputTerms.checked) {
          inputTerms.style.outline = '2px solid #ef4444';
          setTimeout(function () { inputTerms.style.outline = ''; }, 2000);
          isValid = false;
        }

        if (!isValid) return;

        // Form valid! Store locally to simulate submission
        var submissionData = {
          qu_te_interesa_ms_ahora_mismo: selectedVal,
          nombre: inputNombre.value.trim(),
          correo_electronico: inputEmail.value.trim(),
          numero_de_telefono: document.getElementById('vw-phone-country').value + ' ' + inputPhone.value.trim(),
          timestamp: new Date().toISOString()
        };
        localStorage.setItem('pagurai_form_submission', JSON.stringify(submissionData));

        // Display success/loading state
        var submitBtn = modalForm.querySelector('.vw-popup-submit-btn');
        submitBtn.disabled = true;
        submitBtn.style.backgroundColor = '#0098FF';
        submitBtn.textContent = getTranslation(currentLang, 'form.sending') || 'Sending...';

        // Redirect based on selected option
        setTimeout(function () {
          if (selectedVal === 'Reducir costes de producción de mis anuncios') {
            window.location.href = 'https://artista.videway.com/metodo-richard';
          } else {
            window.location.href = 'https://artista.videway.com/video-acceso';
          }
        }, 1200);
      });
    }

  }

  // Run on page loading
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', initVidewayAcademy);
  } else {
    initVidewayAcademy();
  }
})();
